WIP bashly package install command

diff --git a/homerepo b/homerepo
--- a/homerepo
+++ b/homerepo
@@ -61,6 +61,12 @@ homerepo_usage() {
     echo
 
     # :environment_variable.usage
+    printf "  %s\n" "$(yellow "INSTALLERS_DIR")"
+    printf "    directory storing package bundler scripts and installer scripts for distros\n"
+    printf "    %s\n" "Default: $(dirname $(realpath $0))/installers"
+    echo
+
+    # :environment_variable.usage
     printf "  %s\n" "$(yellow "TEST_DIR")"
     printf "\n"
     printf "    %s\n" "Default: ${REPO_ROOT}/tests"
@@ -122,7 +128,7 @@ homerepo_install_usage() {
   echo
 
   printf "%s\n" "$(cyan "Usage:")"
-  printf "  homerepo install\n"
+  printf "  homerepo install PACKAGE\n"
   printf "  homerepo install --help | -h\n"
   echo
 
@@ -133,6 +139,14 @@ homerepo_install_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "$(blue "--help, -h")"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(cyan "Arguments:")"
+
+    # :argument.usage
+    printf "  %s\n" "$(white "PACKAGE")"
+    printf "    Name of package install script to run for current distro\n"
     echo
 
   fi
@@ -365,13 +379,13 @@ homerepo_bootstrap_command() {
       local target_path="$(realpath ${d})"
       local backup_path="${CONFIG_BACKUP_DIR}/$(basename ${d})"
       if [ -d ${existing_path} ] && [ ! -L ${existing_path} ]; then
-  	echo "Backing up ${existing_path} to ${backup_path}"
-  	mv ${existing_path} ${backup_path}
+          echo "Backing up ${existing_path} to ${backup_path}"
+          mv ${existing_path} ${backup_path}
       fi
       # FIXME: not working for some reason? Links even if the existing_path is a link
       if [ ! -L ${existing_path} ]; then
       	echo "- ${existing_path} -> ${target_path}"
-      	ln -s ${target_path} ${existing_path}
+      	ln -n -s ${target_path} ${existing_path}
       fi
   done
   echo "Done linking config dirs"
@@ -424,10 +438,61 @@ homerepo_unbootstrap_command() {
 homerepo_install_command() {
 
   # bashly/commands/install.sh
-  echo "# this file is located in 'bashly/commands/install.sh'"
-  echo "# code for 'homerepo install' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+  #!/bin/bash
+  # TODO: make another script for bundlers?
+  # needed args: package
+
+  echo ${INSTALLERS_DIR}
+  echo ${REPO_ROOT}
+  echo ${args[@]}
+  export INSTALLERS_LOGGER_FILE="/tmp/homerepo-install_$(date +%s).log"
+
+  . ${REPO_ROOT}/lib/sh/basic_utils_lib.sh
+  . ${REPO_ROOT}/lib/sh/repo_tools_lib.sh
+
+  show_usage() {
+      echo "Usage: $0 [HOMEREPO_USER]"
+  }
+
+  pre_flight() {
+      # TODO: validate the id command and user properly
+      HOMEREPO_USER=${1:-$(id -un)}
+      if [ -z "$HOMEREPO_USER" ]; then
+          echo "HOMEREPO_USER needs to be set accurately"
+          show_usage
+          exit 1
+      else
+          echo "install for user ${HOMEREPO_USER}"
+      fi
+
+      if ! id "$HOMEREPO_USER" >/dev/null 2>&1; then
+          show_usage
+          echo "User '$HOMEREPO_USER' not found" >&2
+          exit 1
+      fi
+
+      # TODO: validate the home dir, might not have to use getent, but maybe validate HOME vs getent passwd?
+      HOME=
+      export HOME=$(getent passwd "$HOMEREPO_USER" | cut -d: -f6)
+      if [ ! -d "$HOME" ]; then
+          echo "Home directory for user '$HOMEREPO_USER' does not exist" >&2
+          exit 1
+      fi
+
+      if [[ $EUID -e 0 ]]; then
+          echo "Don't run this as root"
+          exit 1
+      fi
+  }
+
+  exec_install_script() {
+      # TODO: get distro information
+      # TODO: create util to match a passed package name with the proper distro script
+      # TODO: exec the script as root and pass all needed args and env vars
+      exec sudo "${REPO_ROOT}/testinstall.sh" "${args[@]}"
+  }
+
+  pre_flight
 
 }
 
@@ -506,10 +571,12 @@ parse_requirements() {
   # :command.environment_variables_default
   export REPO_ROOT="${REPO_ROOT:-$(dirname $(realpath $0))}"
   export BACKUP_DIR="${BACKUP_DIR:-${HOME}/.dotfilebackups}"
+  export INSTALLERS_DIR="${INSTALLERS_DIR:-$(dirname $(realpath $0))/installers}"
   export TEST_DIR="${TEST_DIR:-${REPO_ROOT}/tests}"
 
   env_var_names+=("REPO_ROOT")
   env_var_names+=("BACKUP_DIR")
+  env_var_names+=("INSTALLERS_DIR")
   env_var_names+=("TEST_DIR")
 
   # :command.command_filter
@@ -714,13 +781,25 @@ homerepo_install_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        # :argument.case
+        if [[ -z ${args['package']+x} ]]; then
+          args['package']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+  # :command.required_args_filter
+  if [[ -z ${args['package']+x} ]]; then
+    printf "missing required argument: PACKAGE\nusage: homerepo install PACKAGE\n" >&2
+
+    exit 1
+  fi
 
 }
 
@@ -873,6 +952,7 @@ initialize() {
   # :command.environment_variables_default
   export REPO_ROOT="${REPO_ROOT:-$(dirname $(realpath $0))}"
   export BACKUP_DIR="${BACKUP_DIR:-${HOME}/.dotfilebackups}"
+  export INSTALLERS_DIR="${INSTALLERS_DIR:-$(dirname $(realpath $0))/installers}"
   export TEST_DIR="${TEST_DIR:-${REPO_ROOT}/tests}"
 
 }
